repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [ --fix=lf ]
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: check-json
      - id: debug-statements
      - id: requirements-txt-fixer
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.25.0
    hooks:
      - id: yamllint
        types: [ file ]
        files: ^(.*\.ya?ml(\.example)?|\.yamllint)$
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.10
        args: [ -l , '88' ]
