# Directory management
# --------------------
directory_management:

  #: String: Path of the file containing the data (Required)
  data_path: data/

  #: String: Path of the directory in which to write result files (Required)
  result_path: results/analyses_test/

 
# File management
#----------------
file_management:
 
  #: String: name of the file containing the data
  original_data_file: data_test.csv
 
  #: String: type of file
  #: Possible type of files:

  #: * :code: `csv`
  #: * :code: `xlsx`

  #: (Required)

  table: csv

  #: Bool: index (row number) in your table
  #: Possible index:

  #: * :code: `True`
  #: * :code: `False`

  #: (Required)

  index: True

  #: String: separator between columns
  #: Possible separators FOR CSV FILES ONLY:

  #: * :code: "," comma separator
  #: * :code: ";" semicomma separator
  #: * :code: "\t" tabulation separator

  #: (Required)
  sep: ","

  #: String: output files (view README.md for details)
  quantitative_test: anova.csv
  quantitative_enrichment: quantitative_gaussian.csv
  qualitative_test: Chi2.csv
  qualitative_enrichment: qualitative_hypergeometric.csv
  variable_weight: weight.csv


# Variable management 
#-------------------
variable_management:

  #: String: [names of the variables] for the qualitative variables
  qualitative_variables: ["type","strand"]
  
  #: String: [names of the variables] for the quantitative variables
  quantitative_variables: ["nb_dupli","length"]
  
  #: String: name of the cluster variable
  factor_variable: chr


# Thresholds tests
#-------------------
thresholds_management:

  #: Float: threshold for the anova test
  anova_threshold: 0.01

  #: Float: threshold for gaussian distribution
  gaussian_threshold: 0.01

  #: Float: threshold for the X2 test
  x2_threshold: 0.05

  #: Float: threshold for hypergeometric distribution
  hypergeometric_threshold: 0.05


# Missing data management
#----------------
missing_data_management:
 
  #: String: choice of quantitative missing data management
  #: Possible type of quantitative missing data management:

  #: * :code: `drop`
  #: * :code: `zero`
  #: * :code: `mean`

  #: (Required)

  quanti_missing_data : zero

  #: String: choice of qualitative missing data management
  #: Possible type of qualitative missing data management:

  #: * :code: `drop`
  #: * :code: "modality user choose"

  #: (Required)

  quali_missing_data : "missing values"


# Color management
#-----------------------------------
figure_management:

  #: String: color palette for the sunburst qualitative analysis and statistic to show in the sunburst
  #: Possible color are present in the plotly_colors.txt file
  over_represented: yellowgreen
  under_represented: slateblue
  not_significant: black
  general_color: wheat

  #: String: choose one among QuaDS statistics
  #: Possible QuaDS statistics:

  #: * :code: `mod/cla`
  #: * :code: `cla/mod`
  #: * :code: `global`

  #: (Required)

  statistic: mod/cla


# File logging
#-------------
logging:

  #: String: Define log level
  #:
  #: Possible log levels:
  #:
  #: * :code: `twice` standard level. Information in console and Logger
  #: * :code:`console` , informations only in the console
  #: * :code:`logger`, informations only in the logger
  #:
  #: (Required)
  log_level: twice

  #: String: Location of the log file (path and file name) (Required)
  log_file: quads.log
