# Directory management
# --------------------
directory_management:

  #: String: Path of the file containing the original rose data (Required)
  data_path: data/

  #: String: Path of the directory in which to write result files (Required)
  result_path: results/analyses_test/

 
# File management
#----------------
file_management:
 
  #: String: name of the file containing the data
  original_data_file: data_test.csv
 
  #: String: type of file
  #: Possible type of files:

  #: * :code: csv
  #: * :code: xslx

  #: (Required)

  table: csv

  #: Bool: index (row names) in your table
  #: Possible index:

  #: * :code: True
  #: * :code: False

  #: (Required)

  index: True

  #: String: separator between columns
  #: Possible separators:

  #: * :code: "," comma separator
  #: * :code: ";" semicomma separator
  #: * :code: "\t" tabulation separator

  #: (Required)
  sep: ","

  #: String: output files (view README.md for details)
  quantitative_test: anova.csv
  quantitative_enrichment: quantitative_gaussian.csv
  qualitative_test: Chi2.csv
  qualitative_enrichment: qualitative_hypergeometric.csv
  variable_weight: weight.csv


# Variable management 
#-------------------
variable_management:

  #: String: [names of the variables] for the qualitative variables
  qualitative_variables: ["type","strand"]
  
  #: String: [names of the variables] for the quantitative variables
  quantitative_variables: ["nb_dupli","length"]
  
  #: String: name of the cluster variable
  cluster_variable: chr

# Thresholds tests
#-------------------
thresholds_management:

  #: Float: threshold for the anova test
  anova_threshold: 0.01

  #: Float: threshold for the X2 test
  x2_threshold: 0.01

  #: Float: threshold for hypergeometric distribution
  hypergeometric_threshold: 0.01

  #: Float: threshold for gaussian distribution
  gaussian_threshold: 0.01


# Color management
#-----------------------------------
figure_management:

  #: String: color palette for the sunburst qualitative analysis and statistic to show in the sunburst
  #: Possible color are present in the plotly_colors.txt file
  over_represented: red
  under_represented: blue
  not_significant: wheat

  #: String: choose one among QuaDS statistics
  #: Possible QuaDS statistics:

  #: * :code: mod/cla
  #: * :code: cla/mod
  #: * :code: global

  #: (Required)

  statistic: mod/cla


# File logging
#-------------
logging:

  #: String: Define log level
  #:
  #: Possible log levels:
  #:
  #: * :code:`INFO` standard level. Only produces final images and CSV measurement files
  #: * :code:`DEBUG` level to use to generate trace images
  #:
  #: (Required)
  log_level: INFO

  #: String: Location of the log file (path and file name) (Required)
  log_file: quads.log
